import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import {
  FileText,
  Clock,
  Sparkles,
  TrendingUp,
  AlertCircle,
  FlaskConical,
  Search,
  Filter,
  BookOpen,
  Database,
  MessageSquare,
  CheckCircle2,
  Loader2,
  FolderOpen,
  KeyRound,
  X,
} from "lucide-react";
import { useAuth } from "@/shared/hooks/useAuth";
import { listWorkspacePapers, listWorkspaces } from "@/features/workspaces/api/workspaces-api";
import type { WorkspaceDto, WorkspacePaperDto } from "@/features/workspaces/types";
import { getApiErrorMessage } from "@/features/workspaces/utils/api-error";
import { isAxiosError } from "axios";
import { fetchAgentActivities } from "@/features/ai-agent/api/agentApi";
import { formatDistanceToNow, parseISO } from "date-fns";

export function Dashboard() {
  const { user, isAuthenticated, logout } = useAuth();
  const navigate = useNavigate();

  const [workspaces, setWorkspaces] = useState<WorkspaceDto[]>([]);
  const [paperCounts, setPaperCounts] = useState<Record<string, number>>({});
  const [projectsLoading, setProjectsLoading] = useState(false);
  const [projectsError, setProjectsError] = useState<string | null>(null);

  const [activities, setActivities] = useState<any[]>([]);
  const [activitiesLoading, setActivitiesLoading] = useState(false);
  const [selectedActivity, setSelectedActivity] = useState<any | null>(null);
  const [pollActivities, setPollActivities] = useState(false);

  const getActivityMeta = (name: string) => {
    switch (name) {
      case "Finder":
        return { icon: Search, badge: "bg-purple-100 text-purple-700", iconWrap: "bg-purple-100", iconColor: "text-purple-700" };
      case "Reader":
        return { icon: BookOpen, badge: "bg-pink-100 text-pink-700", iconWrap: "bg-pink-100", iconColor: "text-pink-700" };
      case "Q&A":
        return { icon: MessageSquare, badge: "bg-green-100 text-green-700", iconWrap: "bg-green-100", iconColor: "text-green-700" };
      case "Action":
        return { icon: Database, badge: "bg-orange-100 text-orange-700", iconWrap: "bg-orange-100", iconColor: "text-orange-700" };
      case "Synthesizer":
        return { icon: Sparkles, badge: "bg-indigo-100 text-indigo-700", iconWrap: "bg-indigo-100", iconColor: "text-indigo-700" };
      case "Critic":
        return { icon: CheckCircle2, badge: "bg-amber-100 text-amber-700", iconWrap: "bg-amber-100", iconColor: "text-amber-700" };
      case "Refiner":
        return { icon: Filter, badge: "bg-blue-100 text-blue-700", iconWrap: "bg-blue-100", iconColor: "text-blue-700" };
      case "Supervisor":
        return { icon: AlertCircle, badge: "bg-slate-100 text-slate-700", iconWrap: "bg-slate-100", iconColor: "text-slate-700" };
      default:
        return { icon: Sparkles, badge: "bg-slate-100 text-slate-700", iconWrap: "bg-slate-100", iconColor: "text-slate-700" };
    }
  };

  const getActivityTopic = (state: any) => {
    if (!state || typeof state !== "object") return "Research Task";
    const refined = state.refined_query || "";
    const original = state.original_query || "";
    const fallback = refined || original;
    if (!fallback) return "Research Task";
    return String(fallback).split(" ").slice(0, 6).join(" ");
  };

  const getActivitySummary = (name: string, state: any) => {
    const topic = getActivityTopic(state);
    
    switch (name) {
      case "Synthesizer":
        return `Synthesize: ${topic}`;
      case "Critic":
        return `Provide feedback on the artifact generated by synthesizer agent in ${topic}`;
      case "Finder":
        if (state && Array.isArray(state.papers_list) && state.papers_list.length > 0) {
          return `Find related papers for ${topic}`;
        }
        return `Execute discovery task for ${topic}`;
      case "Reader":
        if (state && Array.isArray(state.papers_list) && state.papers_list.length > 0) {
          return `Extract data from ${state.papers_list.length} papers for ${topic}`;
        }
        return `Read research papers for ${topic}`;
      case "Action":
        return `Manage workspace actions for ${topic}`;
      case "Supervisor":
        return `Supervise workflow for ${topic}`;
      case "Refiner":
        if (state?.refined_query) {
          return `Refine query to: ${state.refined_query}`;
        }
        return `Refine user query for ${topic}`;
      case "Q&A":
        return `Process Q&A for ${topic}`;
      default:
        if (state && typeof state === "object" && state.action_status) {
          return String(state.action_status).split("\n")[0];
        }
        return `${getAgentLabel(name)} working on ${topic}.`;
    }
  };

  const getWorkspaceLabel = (item: any) => {
    if (item?.workspace_name) return item.workspace_name;
    return "Unknown Workspace";
  };

  const getAgentLabel = (name: string) => {
    switch (name) {
      case "Finder":
        return "Discovery Agent";
      case "Reader":
        return "Reader/Extractor";
      case "Q&A":
        return "Q&A Agent";
      case "Action":
        return "Workspace Action";
      case "Refiner":
        return "Query Refinement";
      default:
        return `${name} Agent`;
    }
  };

  const formatAgentState = (state: any) => {
    if (!state || typeof state !== "object") {
      return [] as Array<{ label: string; value: string }>;
    }

    const details: Array<{ label: string; value: string }> = [];
    if (state.refined_query) details.push({ label: "Refined query", value: String(state.refined_query) });
    if (Array.isArray(state.papers_list)) details.push({ label: "Papers found", value: String(state.papers_list.length) });
    if (Array.isArray(state.selected_paper_ids)) details.push({ label: "Papers selected", value: String(state.selected_paper_ids.length) });
    if (Array.isArray(state.extracted_data)) details.push({ label: "Extracted papers", value: String(state.extracted_data.length) });
    if (typeof state.critic_iterations === "number") details.push({ label: "Critic iterations", value: String(state.critic_iterations) });
    if (state.action_status) details.push({ label: "Action status", value: String(state.action_status) });
    if (state.synthesis_draft) details.push({ label: "Synthesis length", value: `${String(state.synthesis_draft).length} chars` });
    return details;
  };

  const loadProjects = useCallback(async () => {
    if (!isAuthenticated) {
      setPaperCounts({});
      setProjectsLoading(false);
      setProjectsError(null);
      return;
    }

    setProjectsLoading(true);
    setProjectsError(null);
    try {
      const links = await listWorkspacePapers().catch(() => [] as WorkspacePaperDto[]);

      const counts: Record<string, number> = {};
      for (const l of links) {
        const key = String(l.workspace);
        counts[key] = (counts[key] ?? 0) + 1;
      }
      setPaperCounts(counts);
    } catch (err) {
      if (isAxiosError(err) && err.response?.status === 401) {
        await logout();
        navigate("/login", { replace: true });
        return;
      }
      setProjectsError(getApiErrorMessage(err, "Could not load workspaces"));
    } finally {
      setProjectsLoading(false);
    }
  }, [isAuthenticated, logout, navigate]);

  const loadActivities = useCallback(async () => {
    if (!isAuthenticated) {
      setActivities([]);
      return;
    }
    setActivitiesLoading(true);
    try {
      const data = await fetchAgentActivities();
      setActivities(data.activities);
      setWorkspaces(data.workspaces);
      setPaperCounts(data.paperCounts || {});
    } catch (err) {
      console.error("Failed to load agent activities", err);
    } finally {
      setActivitiesLoading(false);
    }
  }, [isAuthenticated]);

  useEffect(() => {
    void loadProjects();
    void loadActivities();

    const handleUpdate = () => void loadActivities();
    window.addEventListener("sagent:activity-updated", handleUpdate);

    return () => {
      window.removeEventListener("sagent:activity-updated", handleUpdate);
    };
  }, [loadProjects, loadActivities, isAuthenticated]);

  useEffect(() => {
    const handleStart = () => {
      setPollActivities(true);
      void loadActivities();
    };
    const handleStop = () => setPollActivities(false);

    window.addEventListener("sagent:activity-poll-start", handleStart);
    window.addEventListener("sagent:activity-poll-stop", handleStop);

    return () => {
      window.removeEventListener("sagent:activity-poll-start", handleStart);
      window.removeEventListener("sagent:activity-poll-stop", handleStop);
    };
  }, [loadActivities]);

  useEffect(() => {
    if (!isAuthenticated || !pollActivities) return;
    const interval = setInterval(() => {
      void loadActivities();
    }, 10000);
    return () => clearInterval(interval);
  }, [isAuthenticated, pollActivities, loadActivities]);

  const activeWorkspaces = useMemo(() => workspaces.slice(0, 4), [workspaces]);

  return (
    <div className="p-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-slate-900 mb-2">Research Dashboard</h1>
          <p className="text-slate-600">{isAuthenticated ? `Welcome back, ${user.name}. Here's an overview of your research projects.` : "Welcome to Sagent. Here's an overview of research insights."}</p>
        </div>

        {/* Projects Grid */}
        <div className="mb-8">
          <h2 className="text-slate-900 mb-4">Active Projects</h2>
          {projectsLoading ? (
            <div className="flex items-center justify-center py-10 text-slate-600 gap-2">
              <Loader2 className="w-5 h-5 animate-spin" aria-hidden />
              Loading workspaces…
            </div>
          ) : projectsError ? (
            <div className="bg-white rounded-xl border border-slate-200 p-6">
              <p className="text-sm text-red-700">{projectsError}</p>
              <button
                type="button"
                onClick={() => void loadProjects()}
                className="mt-3 inline-flex items-center gap-2 px-4 py-2 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 transition-colors"
              >
                Retry
              </button>
            </div>
          ) : !isAuthenticated ? (
            <div className="bg-white rounded-xl border border-slate-200 p-10 text-center">
              <KeyRound className="w-12 h-12 text-slate-300 mx-auto mb-4" />
              <h3 className="text-slate-900 mb-2">Log in to view your workspaces</h3>
              <p className="text-slate-600 mb-6">Active projects are pulled from your workspaces.</p>
              <Link
                to="/login"
                className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                <KeyRound className="w-4 h-4" />
                Log in
              </Link>
            </div>
          ) : activeWorkspaces.length === 0 ? (
            <div className="bg-white rounded-xl border border-slate-200 p-10 text-center">
              <FolderOpen className="w-12 h-12 text-slate-300 mx-auto mb-4" />
              <h3 className="text-slate-900 mb-2">No workspaces yet</h3>
              <p className="text-slate-600 mb-6">Create a workspace to start organizing papers.</p>
              <Link
                to="/workspace"
                className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                Go to Workspaces
              </Link>
            </div>
          ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
            {activeWorkspaces.map((ws) => (
              <Link
                key={ws.id}
                to="/workspace"
                className="block bg-white rounded-xl border border-slate-200 p-6 hover:border-blue-300 hover:shadow-lg transition-all"
              >
                <div className="flex items-start justify-between mb-4">
                  <div className="flex-1">
                    <h3 className="text-slate-900 mb-2">{ws.name}</h3>
                    <div className="flex items-center gap-4 text-sm text-slate-600">
                      <div className="flex items-center gap-1">
                        <FileText className="w-4 h-4" />
                        <span>{paperCounts[ws.id] ?? 0} papers</span>
                      </div>
                      <div className="flex items-center gap-1">
                        <Clock className="w-4 h-4" />
                        <span>Created {new Date(ws.created_date).toLocaleDateString()}</span>
                      </div>
                    </div>
                  </div>
                  <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center">
                    <FileText className="w-6 h-6 text-white" />
                  </div>
                </div>

                {/* AI Agent Status */}
                <div className="p-3 rounded-lg flex items-start gap-2 bg-blue-50 border border-blue-200">
                  <Sparkles className="w-4 h-4 mt-0.5 flex-shrink-0 text-blue-600" />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-slate-900 line-clamp-2">
                      {ws.description?.trim() ? ws.description : "Open workspace to view linked papers and AI insights."}
                    </p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
          )}
        </div>

        {/* Quick Actions */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <Link
            to="/discovery"
            className="bg-gradient-to-br from-indigo-500 to-indigo-600 rounded-xl p-6 text-white hover:shadow-xl transition-all"
          >
            <div className="flex items-center justify-between mb-3">
              <Search className="w-8 h-8" />
              <Sparkles className="w-6 h-6 opacity-75" />
            </div>
            <h3 className="mb-1">Paper Discovery</h3>
            <p className="text-sm text-indigo-100">Search and discover research papers</p>
          </Link>

          <Link
            to="/synthesis"
            className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl p-6 text-white hover:shadow-xl transition-all"
          >
            <div className="flex items-center justify-between mb-3">
              <FlaskConical className="w-8 h-8" />
              <TrendingUp className="w-6 h-6 opacity-75" />
            </div>
            <h3 className="mb-1">Synthesis Lab</h3>
            <p className="text-sm text-blue-100">Compare and synthesize papers</p>
          </Link>

        </div>

        {/* Agent Activity Feed */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <h2 className="text-slate-900">Agent Activity Feed</h2>
              {activitiesLoading && <Loader2 className="w-4 h-4 animate-spin text-slate-400" />}
            </div>
            <div className="flex items-center gap-3">
              <Link
                to="/synthesis"
                className="text-sm text-blue-600 hover:text-blue-700"
              >
                View full feed
              </Link>
              <button 
                onClick={() => void loadActivities()}
                className="text-sm text-blue-600 hover:text-blue-700"
              >
                Refresh
              </button>
            </div>
          </div>
          
          <div className="bg-white rounded-xl border border-slate-200 divide-y divide-slate-200 overflow-hidden">
            {!isAuthenticated ? (
              <div className="p-10 text-center text-slate-500 text-sm">
                Log in to see agent activities.
              </div>
            ) : activities.length === 0 ? (
              <div className="p-10 text-center text-slate-500 text-sm">
                No recent agent activity. Start a research workflow to see agents in action.
              </div>
            ) : (
              activities.slice(0, 5).map((item) => {
                const meta = getActivityMeta(item.name);
                const Icon = meta.icon;
                return (
                  <button
                    type="button"
                    key={item.id}
                    onClick={() => setSelectedActivity(item)}
                    className="w-full text-left p-4 hover:bg-slate-50 transition-colors"
                  >
                    <div className="flex items-start gap-3">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 ${meta.iconWrap}`}>
                        <Icon className={`w-5 h-5 ${meta.iconColor}`} />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <span className={`text-xs font-bold px-2 py-0.5 rounded uppercase tracking-wider ${meta.badge}`}>
                            {getAgentLabel(item.name)}
                          </span>
                          <span className="text-sm text-slate-500">-</span>
                          <span className="text-sm font-medium text-slate-700 truncate">
                            {getWorkspaceLabel(item)}
                          </span>
                        </div>
                        <p className="text-sm text-slate-900 mb-1">
                          {getActivitySummary(item.name, item.state_json)}
                        </p>
                        <p className="text-xs text-slate-500">
                          {formatDistanceToNow(parseISO(item.timestamp), { addSuffix: true })}
                        </p>
                      </div>
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </div>
      </div>

      {selectedActivity && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-900/40 backdrop-blur-sm animate-in fade-in">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col animate-in zoom-in-95">
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-slate-50 rounded-t-2xl">
              <div>
                <h2 className="text-xl font-semibold text-slate-900">
                  {getAgentLabel(selectedActivity.name)} - {getWorkspaceLabel(selectedActivity)}
                </h2>
              </div>
              <button
                onClick={() => setSelectedActivity(null)}
                className="p-2 hover:bg-slate-200 rounded-lg transition-colors text-slate-500 hover:text-slate-900"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="p-6 space-y-4 overflow-y-auto">
              <div className="space-y-1">
                <p className="text-xs uppercase tracking-wide text-slate-500">Timestamp</p>
                <p className="text-sm text-slate-900">
                  {new Date(selectedActivity.timestamp).toLocaleString()}
                </p>
              </div>
              <div className="space-y-1">
                <p className="text-xs uppercase tracking-wide text-slate-500">Workspace</p>
                <p className="text-sm text-slate-900">
                  {getWorkspaceLabel(selectedActivity)}
                </p>
              </div>
              <div className="space-y-1">
                <p className="text-xs uppercase tracking-wide text-slate-500">Agent State</p>
                <p className="text-sm text-slate-900">{getActivitySummary(selectedActivity.name, selectedActivity.state_json)}</p>
              </div>
              <div className="space-y-2">
                <p className="text-xs uppercase tracking-wide text-slate-500">Details</p>
                {formatAgentState(selectedActivity.state_json).length === 0 ? (
                  <p className="text-sm text-slate-500">No state details available.</p>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {formatAgentState(selectedActivity.state_json).map((detail, index) => (
                      <div key={`${detail.label}-${index}`} className="bg-slate-50 border border-slate-200 rounded-lg p-3">
                        <p className="text-xs text-slate-500 mb-1">{detail.label}</p>
                        <p className="text-sm text-slate-900 break-words">{detail.value}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}